# Generated by Django 4.1 on 2025-03-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="section",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="section",
            new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("category", "name")},
        ),
    ]
