# Generated by Django 4.1 on 2025-03-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0003_level_alter_service_unique_together_expertise_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighbour",
            name="expertise",
        ),
        migrations.DeleteModel(
            name="Expertise",
        ),
        migrations.DeleteModel(
            name="Level",
        ),
    ]
