# Generated by Django 4.1 on 2025-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0004_remove_neighbour_expertise_delete_expertise_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="neighbour",
            options={"ordering": ["username"]},
        ),
        migrations.RemoveField(
            model_name="neighbour",
            name="apartment",
        ),
        migrations.AddField(
            model_name="neighbour",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
