# Generated by Django 5.1.7 on 2025-03-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "lend_assist",
            "0005_alter_neighbour_options_remove_neighbour_apartment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="neighbour",
            options={"ordering": ["-username"]},
        ),
        migrations.RemoveField(
            model_name="neighbour",
            name="service",
        ),
    ]
