# Generated by Django 5.1.7 on 2025-03-21 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0006_alter_category_options_alter_neighbour_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="neighbours",
            field=models.ManyToManyField(
                related_name="services", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
