# Generated by Django 5.1.7 on 2025-03-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0007_service_neighbours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="neighbour",
        ),
    ]
