# Generated by Django 5.1.7 on 2025-03-21 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0008_remove_request_neighbour"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="neighbours",
            field=models.ManyToManyField(
                related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
