# Generated by Django 4.2 on 2025-03-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0009_request_neighbours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="request",
            name="reward",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
    ]
