# Generated by Django 4.2 on 2025-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend_assist", "0010_alter_category_options_remove_request_reward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="author_username",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="author_username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
